require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'



target 'StudyReactNative' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])
    permissions_path = '../node_modules/react-native-permissions/ios'

  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications"
  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"

  target 'NotificationsImages' do
    pod 'Firebase/Messaging','~>7.1.0'
    config = use_native_modules!

    use_react_native!(:path => config[:reactNativePath])
    end
  
  

  pre_install do |installer|
    # Disable "Application Extension API Only" flag in pods
    installer.pods_project&.targets&.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = false
        end
      end
    codegen_pre_install(installer)
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    installer.pods_project&.targets&.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = false
        end
      end
    flipper_post_install(installer)
    
  end
  
  
end
